import { Injectable } from '@angular/core';
import { ISentence } from './sentence';
@Injectable({
    providedIn: 'root'
})
export class BookService {

    getSentences(): ISentence[] {
        return [
                {
                    line: "Explosives used to burst a forged steel projectile would be unsuitable as a propelling charge for ejecting and propelling projectiles."
                },
                { line: "Similarly, the explosives used in initiators, such as in primers and fuzes, are so sensitive to shock that only small quantities can be used safely." },
                { line: "NAVSEA OP-4, Ammunition and Explosives Safety Afloat manual, defines the word explosives as those substances or mixtures of substances that when suitably initiated by flame, spark, etc, undergo rapid chemical reactions resulting in the rapid release of energy." },
                { line: "The release of energy is almost invariably accompanied by a rapid and pronounced rise in pressure and temperature." },
                { line: "The rise in pressure usually, but not necessarily, is a consequence of the rapid generation of gas in a much larger volume than that originally occupied by the explosive." },
                { line: "An \"explosion\" - practically instantaneous and violent release of energy." },
                { line: "It results from the sudden chemical change of a solid or liquid substance into gases." },
                { line: "These gases, expanded by the heat of the chemical change, exert tremendous pressure on their containers and the surrounding atmosphere." },
                { line: "HIGH AND LOW EXPLOSIVES" },
                { line: "Military explosives are divided into two general classes, high explosives and low explosives, according to their rate of decomposition." },
                { line: "High explosives are usually nitration products of organic substances, such as toluene, phenol, pentaerythritol, amines, glycerin, and starch, and may be nitrogen-containing inorganic substances or mixtures of both." },
                { line: "TNT is an example of a high explosive." },
                { line: "A high explosive may be a pure compound or a mixture of several compounds with additives. Additives such as powdered metals (aluminum), plasticizing oils, or waxes, that impart desired stability and performance characteristics." },
                { line: "When initiated by a blow or shock, it will decompose almost instantaneously in a manner similar to an extremely rapid combustion or with rupture and rearrangement of the molecules themselves. Gaseous and solid products of reaction are produced." },
                { line: "The disruptive effect of the reaction makes these explosives valuable as a bursting charge but precludes (makes impossible) their use as a low-explosive propellant." },
                { line: "Low explosives are mostly solid combustible materials that decompose rapidly but do not normally detonate." },
                { line: "This action is known as \"deflagration\". Upon ignition and decomposition, low explosives develop a large volume of gases that produce enough pressure to propel a projectile in a definite direction." },
                { line: "The rate of burning is an important characteristic that depends upon such factors as combustion gas pressure, grain size and form, and composition." },
                { line: "Under certain conditions, low explosives may be made to detonate in the same manner as high explosives." },
                { line: "Characteristics Of Explosive Reactions " },
                { line: "The most important characteristics of explosive reactions are as follows:" },
                { line: "An explosive reaction differs from ordinary combustion in the velocity of the reaction." },
                { line: "The velocity of combustion of explosives may vary within rather wide limits, depending upon the kind of explosive substance and upon its physical state." },
                { line: "For high explosives the velocity, or time of reaction, is high (usually in feet per second), as opposed to low explosives, where the velocity is low (usually in seconds per foot)." },
                { line: "An explosive reaction of a high explosive is always accompanied by the rapid liberation of heat." },
                { line: "The amount of heat represents the energy of the explosive and its potential for doing work." },
                { line: "The principal gaseous products of the more common explosives are carbon dioxide, carbon monoxide, water vapor, nitrogen, nitrogen oxides, hydrogen, methane, and hydrogen cyanide." },
                { line: "Some of these gases are suffocating, some are actively poisonous, and some are combustible." },
                { line: "The flame at the muzzle of a gun results from the burning of these gases." },
                { line: "Solid residues of the explosives remaining in the gun have been known to ignite when brought into contact with air as the breech is opened." },
                { line: "The ignition may come from high temperature of the gas or from the burning residue in the gun bore." },
                { line: "The resulting explosion may transmit flame to the rear of the gun, producing what is called a \"flareback\". This danger has led to the adoption of gas-expelling devices on guns installed in enclosed compartments or mounts." },
                { line: "The high pressure accompanying an explosive reaction is due to the formation of gases that are expanded by the heat liberated in the reaction." },
                { line: "The work that the reaction is capable of performing depends upon the volume of the gases and the amount of heat liberated." },
                { line: "The maximum pressure developed and the way in which the energy of the explosion is applied depends further upon the velocity of the reaction." },
                { line: "When the reaction proceeds at a low velocity, the gases receive heat while being evolved, and the maximum pressure is attained comparatively late in the reaction. If in the explosion of another substance the same volume of gas is produced and the same amount of heat is liberated but at a greater velocity, the maximum pressure will be reached sooner and will be quantitatively greater." },
                { line: "However, disregarding heat losses, the work done will be equal." }, 
              { line: "The rapidity with which an explosive develops its maximum pressure is a measure of the quality known as \"brisance\"." }, 
              { line: "A brisant explosive is one in which the maximum pressure is attained so rapidly that a shock wave is formed, and the net effect is to shatter material surrounding or in contact with it." }, 
              { line: "Thus brisance is a measure of the shattering ability of an explosive." }, 
              { line: "The stability of an explosive is important in determining the length of time it can be kept under normal stowage conditions without deterioration and its adaptability to various military uses." }, 
              { line: "A good, general explosive should stand a reasonable exposure to such extremes as high humidity in a hot climate or cold temperatures of arctic conditions." }, 
              { line: "There is no one temperature of ignition or detonation in an explosive for its behavior when heated depends on two factors: the manner of confinement and the rate and manner of heating." }, 
              { line: "It is usually possible, however, to find a small range of temperatures within which a given explosive will ignite or detonate." }, 
              { line: "These so-called \"ignition temperatures\", or explosion temperatures, are useful in setting limits near which it is certainly unsafe to heat an explosive." }, 
              { line: "When an unconfined explosive is heated sufficiently, it may detonate or simply catch fire and burn." }, 
              { line: "Detonation can occur either immediately or after an interval of burning." }, 
              { line: "In general, the likelihood of detonation rises rapidly with increasing confinement because of the resultant rise in pressure." }, 
              { line: "The adaptability of an explosive to loading requirements is an important factor in fixing its range of usefulness." }, 
              { line: "When projectiles are press-loaded, it is necessary to fill them with a granular explosive." }, 
              { line: "On the other hand, cast-loaded munitions require either an explosive having a relatively low melting point or a thermosetting plastic to act as a casting medium." }, 
              { line: "The amount of energy necessary to initiate an explosion is the measure of the sensitivity of the explosive." }, 
              { line: "Sensitivity is an important consideration in selecting an explosive for a particular purpose." }, 
              { line: "For example, the explosive in an armor-piercing projectile must be relatively insensitive; otherwise, the shock of impact would detonate it before it had penetrated to the point desired." }, 
              { line: "The amount of energy necessary to initiate an explosion is the measure of the sensitivity of the explosive." }, 
              { line: "Sensitivity is an important consideration in selecting an explosive for a particular purpose." }, 
              { line: "For example, the explosive in an armor-piercing projectile must be relatively insensitive; otherwise, the shock of impact would detonate it before it had penetrated to the point desired." }, 
              { line: "By Heat - Low explosives are commonly initiated by the application of heat in some form." }, 
              { line: "High explosives will react when sufficient heat is applied, especially if heat is applied suddenly throughout the mass." }, 
              { line: "Initiation by percussion (direct blow) or by friction is simply initiation by heat derived from the energy of these actions." }, 
              { line: "By Shock (detonation) - High explosives in general, such as the main charges of gun projectiles, require the sudden application of a strong shock to initiate the explosive reaction." }, 
              { line: "This shock or detonation is usually obtained by exploding a smaller charge of a more sensitive high explosive that is in contact with or in close proximity to the main charge" }, 
              { line: "The smaller charge can readily be exploded by heat or shock" }, 
              { line: "By Influence - It has frequently been demonstrated that detonation of an explosive mass can be transmitted to other masses of high explosive in the vicinity without actual contact" }, 
              { line: "It has been generally accepted that such transmission is caused either by the passage of an explosive percussion wave from one mass to the other or by fragments" }, 
              { line: "The second explosion occurring under these conditions is said to be initiated by influence" }, 
              { line: "The result is called a \"sympathetic\" detonation or explosion" }, 
              { line: "The distance through which this action may take place varies with the kinds of explosive used, the intervening medium, and certain other conditions." }, 
              { line: "Classification The classification of explosives thus far has been based on characteristics" }, 
              { line: "A more practical classification, from the standpoint of the GM, is based on military uses of the explosives" }, 
              { line: "These classifications are initiating explosives, booster explosives and igniters, propellants, and the main charge1 Initiating Explosives \"Initiating explosives\" are those explosives that serve to initiate the ignition of propellants and the reaction of high explosives" }, 
              { line: "Initiating explosives function when subjected to heat, impact, or friction" }, 
              { line: "Initiating explosives may function by themselves, as does the primer cap in a small-arms cartridge" }, 
              { line: "However, in most instances the initiating charge is the lead element in what is known as an \"explosive train\" An explosive train uses the impulse of an initiating explosive to initiate the chain reaction that leads to the detonation of a main burster charge or ignition of a propellant" }, 
              { line: "2 Booster Explosives Relatively insensitive disrupting explosives require an intermediate charge to increase the shock of the initiating explosive to ensure proper reaction of the main explosive charge" }, 
              { line: "A booster increases the shock of the initiating explosive to a degree sufficient to explode the disrupting explosive" }, 
              { line: "The basic high-explosive train consists of the initiator, the booster, and the main (burster) charge" }, 
              { line: "However, high-explosive trains are often compounded by the addition of intermediate charges and time delays" }, 
              { line: "An intermediate charge functions between the initial charge and the booster to ensure the detonation of the booster" },
              { line: "The large quantity and relatively slow burning rate of gun propellant requires the use of another type of explosive train" }, 
              { line: "The small flame produced by the initiating charge is insufficient to ignite the propellant grains thoroughly to produce an efficient burning rate of the entire charge" }, 
              { line: "An explosive train consisting of an initiating charge, usually a mixture of lead styphnate and nitrocellulose (NC), detonates to ignite a small black powder booster which, in turn, ignites the larger black powder igniter" }, 
              { line: "The black powder igniter is contained in the extension tube" }, 
              { line: "The primer extension tube of a 5\"/54 powder charge is approximately 20 inches long, contains 52 grams of black powder, and has 32 vent holes " }, 
              { line: "A primer is a device used to initiate the burning of a propellant charge by means of a flame" }, 
              { line: "Its explosive train normally consists of a small quantity of extremely sensitive primary high explosive which, when detonated, ignites a small black powder booster which, in turn, ignites the black powder igniter" }, 
              { line: "Primers are classified according to the method of initiation (normally percussion or electric) " },
              { line: "All primers function in a similar manner when initiated" }, 
              { line: "Detonators are used in initiating high-explosive bursting charges" }, 
              { line: "They are similar to primers in that they also contain a small quantity of extremely sensitive initiating explosives" }, 
              { line: "However, a detonator will use a high-explosive booster usually made of a more stable substance than the initiating charge but less stable than the main burster" }, 
              { line: "Detonators are also classified according to the methods of initiation, usually electric or percussion" }, 
              { line: "The primary function of a propellant is to provide a pressure that, acting against an object to be propelled, will accelerate the object to the required velocity" }, 
              { line: "This pressure must be controlled so that it will never exceed the strength of the container in which it is produced, such as guns, rocket motor housing, or pyrotechnic pistols" }, 
              { line: "In addition, propellants must be comparatively insensitive to shock" }, 
              { line: "Propellants may be either liquid or solid (Liquid propellants will not be discussed here, since only solid propellants are used in Navy gun ammunition) Propellants can be classified by such terms as single-base, double-base, triple-base, and composite" }, 
              { line: "Single-base propellants contain only one explosive ingredient, NC" }, 
              { line: "Doublebase and triple-base propellants contain, respectively, nitroglycerine (NG) and nitroguanidine (NQ) in addition to NC" }, 
              { line: "Composite propellants are compositions that contain mixtures of fuel and inorganic oxidants" }, 
              { line: "There are combinations of composite and double-base propellants called composite double-base propellants" }, 
              { line: "Solid propellants are manufactured in the form of flakes, balls, sheets, cords, or perforated cylindrical grains" }, 
              { line: "They are made in various shapes to obtain different types of burning actions" }, 
              { line: "In large guns, 40 mm and over, a cylindrical grain with seven perforations is used, while 20-mm guns use a single perforation" }, 
              { line: "Smaller calibers, including small arms, use flake or ball grains" }, 
              { line: "The cylindrical grains are made in various diameters and lengths, but size is normally stated in web thickness " }, 
              { line: "The different types of burning actions are regressive, neutral, and progressive  Figure 1-3 Solid propellant grainsA propellant is said to be \"regressive burning\" when the surface area of the grains decrease as they burn" }, 
              { line: "An example of a \"neutral burning\" grain is a single perforated grain whose inner surface increases and whose outer surface decreases as it burns" }, 
              { line: "The result of these two actions is that the total surface remains the same" }, 
              { line: "As a multiperforated grain burns, its total burning area increases since it burns from the inside to the outside at the same time" }, 
              { line: "Thus it is called \"progressive burning\" "}, 
              { line: "Main Charge The main charge for explosive projectiles, bombs, mines, torpedo warheads, and other bomb type of ammunition is always a high explosive" }, 
              { line: "These substances must meet certain requirements for military use" }, 
              { line: "In general, they must do the following: Be insensitive enough to withstand the shock of handling, of being fired from a gun, and of impact against armor (only in armor-piercing projectiles)  " }, 
              { line: "Have maximum explosive power" }, 
              { line: "Have stability to withstand adverse stowage conditions" }, 
              { line: "Produce proper fragmentation (only for fragmentation weapons)" }, 
              { line: "Be inexpensive and easy to manufacture from readily available materials "}, 
              { line: "High-explosive charges are loaded into their containers by one of three methods: cast-loading, press-loading, and extrusion (by force)" }, 
              { line: "Cast-loading is performed by pouring the substance as a liquid into a container and letting it solidify" }, 
              { line: "Explosives having no liquid form must be press-loaded (pressed into their container) or incorporated into a liquid casting medium" }, 
              { line: "The combining of certain explosives with plastic binders results in plastic mixtures that can be loaded either by casting or by extrusion (by force)" }, 
              { line: "Specific compounds of these explosives are described in the following section" },  
              { line: "Black Powder Black powder is the oldest explosive known" }, 
              { line: "The ingredients in black powder include saltpeter (potassium nitrate or sodium nitrate), charcoal, and sulfur" }, 
              { line: "It ignites spontaneously at about 300° Celsius (540° Fahrenheit) and develops a fairly high temperature of combustion: 2300° Celsius to 3800° Celsius (4172° Fahrenheit to 6782° Fahrenheit)" }, 
              { line: "The chemical stability of black powder is practically unlimited when stored in airtight containers, but it deteriorates irregularly when exposed to moisture, which it absorbs readily" }, 
              { line: "The term hygroscopic applies to explosives that easily absorb moisture" }, 
              { line: "Black powder is not affected by moderately high temperatures, and it is not subject to spontaneous combustion at ordinary stowage temperatures" }, 
              { line: "It is highly flammable and very sensitive to friction, shock, sparks, and flame" }, 
              { line: "When black powder is ignited, it is extremely quick and violent in its action" }, 
              { line: "The Navy classifies black powder into two types (potassium nitrate and sodium nitrate), depending on the chemical compound used in the base material" }, 
              { line: "These two types are further divided into classes identified by numbers 1 through 9 for potassium nitrate-based black powder and by letters A through C for sodium nitrate-based black powder" }, 
              { line: "2 Uses of Black Powder - The range of use of black powder has decreased with the development of new chemical compounds but, where smoke is no objection, black powder is considered by many to be the best substance available for transmitting flame and producing a quick, hot flame" }, 
              { line: "Currently, black powder is used by the Navy for the following purposes: Classes 1 through 9: JATO, rocket igniters, igniter pads, primers, propelling charges for line-throwing guns, expelling charges for base-ejection shells, pyrotechnic items, relay pellets, igniting charges for illuminating candles, charges in target practice shells, igniter charges in primer detonators, fuze-delay elements, tracer igniters, delay and igniter charges in primer detonators, practice hand grenade fuzes, and Navy squibs" }, 
              { line: "Classes A through C: Saluting charges and practice bombs" }, 
              { line: "Black Powder as a Propellant Black powder as a gun propellant has several disadvantages: (1) it leaves a large amount of residue, (2) it produces large quantities of smoke, (3) it causes rapid erosion of the gun bore, and (4) its velocity of reaction is too rapid\" " }, 
              { line: "For these reasons and the fact that black powder charges do not provide the reproducible results required of modern guns, it was abandoned as a propellant around 1888" }, 
              { line: "This abandonment was hastened by the development of NC 2 Nitrocellulos (NC) NC was first prepared in 1838" }, 
              { line: "However, two main problems had to be solved before it could be used as a gun propellant" }, 
              { line: "First, the velocity of the explosion had to be reduced so that the charge weight required to propel the projectile would not shatter the gun tube" }, 
              { line: "Second, the density had to be increased so that a given charge weight would pack into a reasonable space" }, 
              { line: "The first problem was solved in part by igniting NC instead of firing it with a detonator" }, 
              { line: "The solution to the second problem actually solved both" }, 
              { line: "In 1886, Vielle first colloided or gelatinized NC with alcohol and ether and, thus reduced the burning rate to acceptable levels" }, 
              { line: "The procedure significantly increased the loading density of NC, establishing it as the foundational element in gun propellants used through the present day" }, 
              { line: "Further developments resulted in materials that could be added to improve stowage qualities, reduce or eliminate flash, reduce hygroscopicity, reduce flame temperature, and even increase the propellant force or impetus" }, 
              { line: "Smokeless Powder Smokeless powder is the propellant used in the propelling charges for Navy gun ammunition" }, 
              { line: "It is a uniform ether-alcohol colloid of purified NC to which is added a small quantity of diphenylamine or ethyl centralite to assist in preserving the stability of the powder" }, 
              { line: "Smokeless powder is basically unstable since it contains NC and two volatile substances-ether and alcohol" }, 
              { line: "Its length of usefulness depends largely on the conditions under which it is stowed" }, 
              { line: "Moisture or heat speeds its deterioration; a combination of the two has extremely damaging effects" }, 
              { line: "Classification of Smokeless Powder Smokeless powder is classified into two types: single-base and multi-base" }, 
              { line: "Single-base Powder Multibase powder uses NG and/or NQ in addition to NC as explosive ingredients" }, 
              { line: "Such propellants are commonly called double-base (NC and NG) and triple-base (NC, NG, and NQ)" }, 
              { line: "One double-base and one triple-base propellant are in use today2 Multibase Powder Multibase powder uses NG and/or NQ in addition to NC as explosive ingredients" }, 
              { line: "Such propellants are commonly called double-base (NC and NG) and triple-base (NC, NG, and NQ)" }, 
              { line: "One double-base and one triple-base propellant are in use today" }, 
              { line: "Index of Smokeless Powder Smokeless powder types are assigned class designation letters that designate the chemical makeup of the powder as follows: " }, 
              { line: "SP - Smokeless powder " }, 
              { line: "B - Blended " }, 
              { line: "C - Stabilized by ethyl centralite " }, 
              { line: "D - Stabilized by diphenylamine " }, 
              { line: "F - Flashless powder " }, 
              { line: "G - Includes nitroglycerine and nitroguanidine " }, 
              { line: "N - Nonhygroscopic " }, 
              { line: "W - Reworked by grinding " }, 
              { line: "X - Water-drying process" }, 
              { line: "These letters are followed by a number that indicates the sequence of manufacture" }, 
              { line: "The combination of the letters and the number is termed the index or the lot of the powder" }, 
              { line: "The combinations of the class designation letters are described below" }, 
              { line: "SPC - SPC is a cool-burning, single-base smokeless powder (SP) with ethyl centralite (C) as a stabilizer" }, 
              { line: "SPCF - is a single-base smokeless powder similar to SPC type of powder but containing a flash suppressor to render the powder flashless" }, 
              { line: "SPCF is found in all 5i\"/54 universal charge, full-service propelling charges" }, 
              { line: "SPCG - is a multibase smokeless powder stabilized with ethyl centralite and includes NG and NQ in its composition" }, 
              { line: "Although the designation letter for flashless powder (F) is not used, SPCG is a flashless powder" }, 
              { line: "SPD - is a single-base smokeless powder stabilized with diphenylamine" }, 
              { line: "SPDB - is a blend of diphenylamine-stabilized powders of different lots" }, 
              { line: "The purpose of blending is to provide a uniform index of ample size and desired character from smaller remnant lots" }, 
              { line: "SPDF - is a diphenylamine-stabilized smokeless powder to which a flash inhibitor, such as potassium sulfate, has been added" }, 
              { line: "SPDN is a diphenylamine-stabilized smokeless powder to which nonvolatile materials are added to reduce the hygroscopic tendencies of the propellant" }, 
              { line: "The N stands for nonhygroscopic" }, 
              { line: "SPWF - is a flashless powder made by the reworking of ordinary nonflashless powder" }, 
              { line: "M-6 and M-6+2 propellant designations - equate to the SPDN and SPDF (respectively) descriptions previously provided" }, 
              { line: "These designations are used to describe the propellants used in 76-mm ammunition" }, 
              { line: "The +2 refers to a 2% mixture of potassium sulfate" }, 
              { line: "SPDX - is a diphenylamine-stabilized smokeless powder that is water-dried" }, 
              { line: "In the water-drying process, the powder is seasoned in tanks of warm water to remove volatile solvents, followed by a brief period of air drying" }, 
              { line: "The explosives used as initiating explosives are the primary high explosives mentioned previously in this chapter" }, 
              { line: "They are used in varying amounts in the different primers and detonators used by the Navy and may differ some in sensitivity and in the amount of heat given off" }, 
              { line: "Lead Azide Lead azide has a high-ignition temperature and is today the most commonly used primary explosive" }, 
              { line: "Lead azide is poisonous, slightly soluble in hot water and in alcohol, and highly soluble in a diluted solution of nitric or acetic acid in which a little sodium nitrate has been dissolved" }, 
              { line: "It reacts with copper, zinc, cadmium, or alloys containing such metals, forming an azide that is more sensitive than the original lead azide" }, 
              { line: "Because lead azide does not react with aluminum, detonator capsules for lead azide are made of this metal" }, 
              { line: "The hygroscopicity of lead azide is very low" }, 
              { line: "Water does not reduce its impact sensitivity, as is the case with mercury fulminate" }, 
              { line: "Ammonium acetate and sodium dichromate are used to destroy small quantities of lead azide" }, 
              { line: "Lead azide may be used where detonation is caused by flame or heat" }, 
              { line: "The velocity of detonation is approximately 17,500 feet per second (fps)" }, 
              { line: "Its color varies from white to buff" }, 
              { line: "Lead azide is widely used as an initiating explosive in high-explosive detonator devices" }, 
              { line: "Lead azide, when protected from humidity, is completely stable in stowage" }, 
              { line: "Lead Styphnate There are two forms of lead styphnate-the normal that appears as six-sided monohydrate crystals and the basic that appears as small, rectangular crystals" }, 
              { line: "Lead styphnate is particularly sensitive to fire and the discharge of static electricity" }, 
              { line: "When the styphnate is dry, it can readily ignite by static discharges from the human body" }, 
              { line: "The longer and narrower the crystals, the more susceptible the material is to static electricity" }, 
              { line: "Lead styphnate does not react with metals" }, 
              { line: "It is less sensitive to shock and friction than lead azide" }, 
              { line: "Lead styphnate is slightly soluble in water and methyl alcohol and may be neutralized by a solution of sodium carbonate" }, 
              { line: "The velocity of detonation is approximately 17,000 fps" }, 
              { line: "The color of lead styphnate varies from yellow to brown" }, 
              { line: "Lead styphnate is used as an initiating explosive in propellant primer and high-explosive detonator devices" }, 
              { line: "Diazodinitrophenol (DDNP) DDNP is a yellowish brown powder" }, 
              { line: "It is soluble in acetic acid, acetone, strong hydrochloric acid, and most of the solvents, but is insoluble in water" }, 
              { line: "A cold sodium hydroxide solution may be used to destroy it" }, 
              { line: "Diazodinitrophenol DDNP is desensitized by immersion in water and does not react with it at normal temperatures" }, 
              { line: "It is less sensitive to impact but more powerful than lead azide" }, 
              { line: "The sensitivity of Diazodinitrophenol DDNP to friction is approximately the same as that of lead azide" }, 
              { line: "Diazodinitrophenol DDNP is often used as an initiating explosive in propellant primer devices" }, 
              { line: "Booster explosives are those components of the explosive train that function to transmit and augment the force and flame from the initiating explosive" }, 
              { line: "They ensure the reliable detonation or burning of the main burster charge or propellant charge" }, 
              { line: "Propelling charges use a black powder booster, while high-explosive boosters use one of the following: Tetryl, CH-6, or Composition A-5" }, 
              { line: "Tetryl is a fine yellow crystalline material" }, 
              { line: "When Tetryl is heated, it first melts, then decomposes and explodes" }, 
              { line: "It burns readily and is more easily detonated than explosive D" }, 
              { line: "CH-6 is a mixture of 97% RDX, 1% calcium stearate, 0% polyisobutylene, and 0% graphite" }, 
              { line: "It is a finely divided gray powder that is less toxic and more available than Tetryl" }, 
              { line: "Composition A-5 is a mixture of 98% RDX and 1% stearic acid" }, 
              { line: "There are several high explosives currently used by the Navy as fillers for gun projectiles" }, 
              { line: "The principal explosives are Composition A-3, RDX, and explosive D" }, 
              { line: "These explosives, when combined in various percentages and combinations, produce numerous high explosives with varying degrees of sensitivity, brisance, rate of detonation, and other pertinent characteristics" }, 
              { line: "These principal explosives, and some of their more common derivative explosives, are discussed in the following paragraphs, as well as some explosives that are no longer being used but may still be in some ammunition stocks" }, 
              { line: "Trinitrotoluene (TNT) is a crystalline substance" }, 
              { line: "The importance of TNT as a military explosive is based upon its relative safety in manufacture, loading, transportation, and stowage, and upon its explosive properties" }, 
              { line: "Manufacturing yields are high and production relatively economical" }, 
              { line: "The chemical names for TNT are trinitrotoluene and trinitrotol" }, 
              { line: "Other (commercial) names are Trilite, Tolite, Trinol, Trotyl, Tritolol, Tritone, Trotol, and Triton" }, 
              { line: "TNT is toxic, odorless, comparatively stable, nonhygroscopic, and relatively insensitive" }, 
              { line: "When TNT is pure, it is known as grade A TNT and varies from white to pale yellow" }, 
              { line: "When the proportion of impurities is much greater, the color is darker, often brown, and the chemical is known as grade B TNT" }, 
              { line: "It may be ignited by impact, friction, spark, shock, or heat" }, 
              { line: "TNT does not form sensitive compounds with most metals" }, 
              { line: "The melting point varies between 806° Celsius for grade A (refined TNT) and 76° Celsius for grade B (crude TNT)" }, 
              { line: "TNT does not appear to be affected by acids but is affected by alkalies (lye, washing soda, and so on), becoming pink, red, or brown, and more sensitive" }, 
              { line: "TNT is practically insoluble in water, but soluble in alcohol, ether, benzene, carbon disulfide, acetone, and certain other solvents" }, 
              { line: "The velocity of detonation for TNT is approximately 22,300 fps" }, 
              { line: "Exudate has been known to separate from cast TNT" }, 
              { line: "It may appear pale yellow to brown and may vary in consistency from an oily liquid to a sticky substance" }, 
              { line: "The amount and rate of separation depend primarily upon the purity of the TNT and, secondarily, upon the temperature of the stowage place" }, 
              { line: "Grade B (low-melting point) TNT may exude a considerable amount of liquid and generate some gas" }, 
              { line: "An increase in temperature will accelerate exudation " }, 
              { line: "Pure TNT will not exude since exudate consists of impurities that have not been extracted in jhe refining process" }, 
              { line: "Exudate is a mixture of lower melting isomers of TNT, nitrocompounds of toluene of lower nitration, and possible nitrocompounds of other aromatic hydrocarbons and alcohols" }, 
              { line: "It is flammable and has high sensitivity to percussion when mixed with absorbents" }, 
              { line: "Its presence does no appreciable harm to the stability but somewhat reduces the explosive force of the main charge" }, 
              { line: "In some ammunition, an inert wax pad is used in the loading operation, and, in some cases, waxy material may ooze from the case" }, 
              { line: "It should not be confused with the TNT exudate previously described" }, 
              { line: "This material should, however, be tested for TNT to confirm its actual composition" }, 
              { line: "TNT exudate, when mixed with a combustible material, such as wood chips, sawdust, or cotton waste, will form a low explosive that is highly flammable and ignites easily from a small flame" }, 
              { line: "It can be exploded in a manner similar to a low grade of dynamite, but the main danger is its fire hazard" }, 
              { line: "Accumulation of exudate is considered a great risk of explosion and fire" }, 
              { line: "Its accumulation should always be avoided by continual removal and disposal as it occurs" }, 
              { line: "The exudate is soluble in acetone or alcohol" }, 
              { line: "One of these solvents (requiring adequate ventilation) or clean, hot water should be used to facilitate removal and disposal of the exudate" }, 
              { line: "WARNING: Under no circumstances should soap or other alkaline preparations be used to remove this exudate" }, 
              { line: "The addition of a small amount of hydroxide, caustic soda, or potash will sensitize TNT and cause it to explode if heated to 160° Celsius" }, 
              { line: "HMX (Cyclotetramethylene Tetranitramine) was discovered as a by-product in the production of RDX" }, 
              { line: "Although it is almost as sensitive and powerful as RDX, it is seldom used alone in military applications but is normally mixed with another compound, such as TNT" }, 
              { line: "In the Navy, HMX is used as an ingredient in plastic-bonded explosives" }, 
              { line: "RDX (Cyclotrimethylene Trinitramine) RDX, also known as Cyclonite or Hexogen, is considered the most powerful and brisant of the military high explosives" }, 
              { line: "RDX is also one of the most used high explosives in Navy munitions" }, 
              { line: "RDX is a white crystalline solid that HAS a high degree of stability in stowage" }, 
              { line: "RDX is usually used in mixtures with other explosives, desensitizers, or plasticizers" }, 
              { line: "The most used compositions of RDX are included in the following paragraphs" }, 
              { line: "Composition A-3 is a wax-coated, granular explosive, consisting of 91% RDX and 9% desensitizing wax" }, 
              { line: "Composition A-3 is not melted or cast" }, 
              { line: "Composition A-3 is pressed into projectiles" }, 
              { line: "Composition A-3 is nonhygroscopic and possesses satisfactory stowage properties" }, 
              { line: "Composition A-3 is appreciably more brisant and powerful than TNT; its velocity of detonation is approximately 27,000 fps" }, 
              { line: "Composition A-3 may be white or buff, depending upon the color of the wax used to coat the powdered RDX" }, 
              { line: "Composition A-3 is used as a filler in projectiles that contain a small burster cavity, such as antiaircraft projectiles" }, 
              { line: "Composition A-3 can be used as compressed fillers for medium-caliber projectiles" }, 
              { line: "Composition B is a mixture of 59% RDX, 40% TNT, and 1% wax" }, 
              { line: "The TNT reduces the sensitivity of the RDX to a safe degree and, because of its melting point, allows the material to be cast-loaded" }, 
              { line: "The blast energy of Composition B is slightly higher than that of TNT" }, 
              { line: "Composition B is nonhygroscopic and remains stable in stowage" }, 
              { line: "Composition B has an extremely high-shaped-charge efficiency" }, 
              { line: "The velocity of detonation is approximately 24,000 fps, and its color ranges from yellow to brown" }, 
              { line: "Composition B has been used as a more powerful replacement for TNT in loading some of the rifle grenades and some rocket heads" }, 
              { line: "Composition B can be used where an explosive with more power and brisance is of tactical advantage and there is no objection to a slight increase of sensitivity" }, 
              { line: "While no longer used in newer gun projectiles, some older stocks may be found with Composition B main charges" }, 
              { line: "Composition C-3 is one of the Composition C series that has now been replaced by C-4, especially for loading shaped charges" }, 
              { line: "However, quantities of Composition C-1 and Composition C-2 may be found in the field" }, 
              { line: "Composition C-1 is 88% RDX and 11 7% plasticizing oil" }, 
              { line: "Composition C-3 is 77% RDX, 3% tetryl, 4% TNT, 1% NC, 5% MNT (mononitrotoluol), and 10% DNT (dinitrotoluol)" }, 
              { line: "The last two compounds, while they are explosives, are oily liquids and plasticize the mixture" }, 
              { line: "The essential difference between Composition C-3 and Composition C-2 is the substitution of 3% tetryl for 3% RDX, which improves the plastic qualities" }, 
              { line: "The changes were made in an effort to obtain a plastic, puttylike composition to meet the requirements of an ideal explosive for molded and shaped charges that will maintain its plasticity over a wide range of temperatures and not exude oil" }, 
              { line: "Composition C-3 is about 15 times as powerful as TNT" }, 
              { line: "The melting point of Composition C-3 is 68° Celsius, and it is soluble in acetone" }, 
              { line: "The velocity of detonation is approximately 26,000 fps" }, 
              { line: "C-3 is light brown" }, 
              { line: "As with Composition B, Composition C is no longer being used as a gun projectile main charge" }, 
              { line: "However, some stocks may still be in service with Composition C-3 used as a main charge" }, 
              { line: "Explosive D (ammonium picrate) is a yellow crystalline material" }, 
              { line: "Explosive D is less sensitive than TNT or Composition A-3 and is generally used in projectiles that must penetrate hard targets, such as armor, without detonating" }, 
              { line: "Plastic-Bonded Explosives PBXs are relatively new types of explosive compositions that have found increased use in naval weapons" }, 
              { line: "They are generally made of an explosive compound like RDX or HMX incorporated into either an energetic or inert plastic binder" }, 
              { line: "PBXN-5 - is referred to as a plastic-bonded explosive because it is an explosive coated with plastic material" }, 
              { line: "The composition is made of 95% HMX and 5% fluoroelastomers" }, 
              { line: "PBXN-106 - this explosive is one of the new plastic-bonded explosives" }, 
              { line: "It is a cast-cured explosive composition made from a homogenous mixture of RDX in a plasticized polyurethane rubber matrix" }, 
              { line: "Once cured, the material cannot be easily restored to a liquid state" }, 
              { line: "The finished PBXN-106 is flexible and will absorb considerably more mechanical shock than conventional cast or pressed explosives" }, 
              { line: "Pyrotechnic is the Greek word for fireworks" }, 
              { line: "The Navy uses fireworks not for celebration, but for illumination, marking, and signaling" }, 
              { line: "An example is the illuminating projectile, or star shell, used to illuminate targets for gunfire" }, 
              { line: "A star shell actually is a pyrotechnic device, although it is encased in a projectile body of standard external shape and is fired from a standard rifled gun" }, 
              { line: "For further information on these and other pyrotechnic devices used by the Navy, refer to Pyrotechnic, Screening, Marking, and Countermeasure Devices, NAVSEA SW050-AB-MMA-010" }, 
              { line: "All the pyrotechnics we study here are intended for signaling and marking · · · marine location markers marine illumination signals and the pyrotechnic pistol, projector, and projectiles used in firing them distress and hand signals" }, 
              { line: "Marine location markers are used as night or day long-burning reference markings on the surface of the ocean" }, 
              { line: "They are dropped over the side from surface ships for manoverboard marking, navigation drills, and other similar operations" }, 
              { line: "These markers may also be dropped from aircraft for search and rescue operations" }, 
              { line: "The two marine location markers currently in use are the Mk 58 and the Mk 6" }, 
              { line: "Mk 58 Marine Location Marker The Mk 58 marine location marker is the primary marine location marker found aboard surface vessels" }, 
              { line: "It is approximately 21 1/2 inches long and weighs about 12 3/4 pounds" }, 
              { line: "It contains a battery squib, some starter mix, two pyrotechnic candles, and a transfer fuse be tween the two candles" }, 
              { line: "Before launching, the tear tape over the water port must be removed so that seawater can enter to activate the battery" }, 
              { line: "Battery current energizes the electric squib, which ignites the starter mix, which, in turn, lights the pyrotechnic candle" }, 
              { line: "When the first candle has burned out (in 20 to 30 minutes), the second candle is started by the transfer fuze for a total burning time of approximately 40 to 60 minutes" }, 
              { line: "The Mk 58 currently is available in two versions: the Mod 0 and the Mod 1" }, 
              { line: "The Mod 0 is a hermetically sealed can that is opened with a twist key" }, 
              { line: "Mk 6 Marine Location Markers - The Mk 6 aircraft smoke and illumination signal (Marker) is a pyrotechnic device that is launched from surface craft only to produce a day or night floating reference point" }, 
              { line: "One of its principal uses is as a man-overboard marker" }, 
              { line: "It was previously approved for launching from low-performance aircraft as a long-burning marker but has been replaced for this purpose by the Mk 58 marine location marker" }, 
              { line: "The Mk 6 signal consists of a wooden body with a flat, die-cast metal plate affixed to one end to protect it from water impact damage and to maintain it in the correct floating attitude" }, 
              { line: "There are four flame and smoke emission holes in the opposite end, each capped and sealed with tape" }, 
              { line: "The pull-wire ring, also at the emission end, is also covered with tape" }, 
              { line: "The Mk 6 signal has a direct-firing ignition system" }, 
              { line: "Ignition results from pulling the pull ring" }, 
              { line: "The pull ring is pulled by hand, and the device is thrown into the water immediately" }, 
              { line: "The pull wire ignites a 90-second delay fuse that ignites the quick match at the top of the first of four candles" }, 
              { line: "The quick match ignites the first candle starting mix, which, in turn, initiates burning of that candle" }, 
              { line: "Expanding gases of combustion force the cap and tape from the emission hole, allowing smoke and flame to be emitted" }, 
              { line: "When the first candle is nearly burned out, a transfer fuse carries the ignition to the quick match of the next candle in series" }, 
              { line: "This process continues until all four candles have burned" }, 
              { line: "The yellow flame and gray-white smoke are produced for a minimum of 40 minutes" }, 
              { line: "After the tear strip on the shipping container has been removed, the following rules apply: · The tape over the pull ring should not be disturbed until immediately before hand launching the signal" }, 
              { line: "This tape not only prevents an accidental pull on the pull ring but also protects the igniter assembly from moisture, which might render the signal useless WARNING This signal is initiated by the physical movement of a friction wire through ignition compound" }, 
              { line: "Extreme care must be taken to prevent tension of the pull ring during all handling operations" }, 
              { line: "If this device is prepared for launching and is not launched, the pull ring should be securely retaped into position at the top of the signal without exerting any pulling force on the pull-wire igniter" }, 
              { line: "Under no circumstances should these signals be stowed or restowed with their pull rings exposed or with any wires, strings, or other material of any kind joined to their pull ringsAll safety precautions pertaining to this signal must be observed" }, 
              { line: "In addition, the following specific rules apply: " }, 
              { line: "Do not remove the tape over the pull ring until immediately before launching" }, 
              { line: "The Mk 6 signal should be thrown over the side immediately after pulling the pull ring" }, 
              { line: "This device contains a maximum 90-second delay element between initiation and candle ignition" }, 
              { line: "In all handling, extreme care should be taken to avoid pulling on the pull ring" }, 
              { line: "The slightest movement of the friction igniter may start the ignition trainThe Mk 6 marine location marker is being replaced by the Mk 58" }, 
              { line: "Remaining serviceable stocks of the Mk 6 are still available and should be used first" }, 
              { line: "Man-overboard and navigation drills are good instances where these stocks can be efficiently expended3 Mk25 Marine Location Marker Although this device, , is designed to be launched either from aircraft or surface craft, it is primarily launched from aircraft to provide either day or night reference points in marking the course of enemy submarines in antisubmarine warfare operations" }, 
              { line: "It is suitable, however, for any type of sea-surface reference point marking that calls for both smoke and flame for a period of approximately 15 minutes" }, 
              { line: "Because of its improved design, its launchability at higher aircraft speeds, its greater reliability, and its lower unit cost, this marker has replaced Aircraft Smoke and Illumination Signal Mk 5 Mods and Marine Location Marker Mk 9 Mod 0" }, 
              { line: "The Mk 25 marker is to be launched from aircraft only in accordance with the flight manual or the Conventional Weapons Loading Manual for the particular aircraft being employed" }, 
              { line: "Mk 25 marker may be hand launched, or it may be dispensed from the Aero 1A or 1B retro-launcher, the free-fall Marine Marker Dispenser, the Sonobuoy Launcher, or the Marine Marker Launcher Assembly" }, 
              { line: "When the free-fall dispenser is used, Marine Marker Adapter Kit Mk 34 Mod 0 shall be used" }, 
              { line: "Both currently available mods of this device function identically" }, 
              { line: "The only significant difference is that Mod 2 contains two water-activated batteries and two related squibs, whereas Mod 3 contains a single battery and squib" }, 
              { line: "This marker consists of a cylindrical outer tube approximately 18 inches long and 3 0 inches in diameter" }, 
              { line: "There is a projecting chimney at its nose end into which is fitted a valve assembly" }, 
              { line: "At the opposite end is a heavier aluminum base assembly to which the outer tube is crimped" }, 
              { line: "Within the base assembly is a Mk 72 Mod 0 Water-Activated Battery (two such batteries in Mod 2)" }, 
              { line: "The battery is shielded from water contact by two plugs which are fitted into 1/2 inch holes on two opposite sides of the base assembly" }, 
              { line: "A ring ridged cover (arming plate), held in place by a retainer ring, is recessed into the base end" }, 
              { line: "An arrow in the center of the arming plate indicates its safe or armed position" }, 
              { line: "The words 'Safe' and 'Armed' are stamped into the base rim, and a notch has been cut into the rim at the armed position to facilitate nighttime use" }, 
              { line: "A black rubber Gring, which serves as a gas check in pneumatic dispensing, encircles the base assembly approximately 1/4 inch from the crimp holding the outer case" }, 
              { line: "WARNING: KEEP THE MARKER COMPLETELY AWAY FROM WATER AFTER THE PLUGS ARE PUSHED IN" }, 
              { line: "SALT WATER ON THE BATTERY WILL CAUSE THE MARKER TO FUNCTION WITHIN 10 TO 20 SECONDS" }, 
              { line: "While this marker was designed to be used in sea water, it may be employed in inland bodies of non-salt water by adopting the following procedure: " }, 
              { line: "Obtain table salt" }, 
              { line: "Using the pliers, remove the retainer ring from its position, holding the cover (arming plate) in the base of the marker" }, 
              { line: "Remove the cover (arming plate) by pulling it out" }, 
              { line: "Add ½ to ¾ ounce (1 level table-spoon) of table salt to battery cavity" }, 
              { line: "Replace cover (arming plate) and ensure that the arrow in center points toward the word 'Safe'" }, 
              { line: "Replace the retainer ring so that it holds the cover securely" }, 
              { line: "Mark the unit to indicate that salt has been added to the fuze cavity for conversion for use in fresh waterLaunching by Hand" }, 
              { line: "The following steps shall be taken in hand launching Marine Location Marker Mk 25 Mods: 1" }, 
              { line: "Remove a marker from its shipping container and inspect it for damage of any kind" }, 
              { line: "Dented, corroded, or otherwise damaged markers should not be used" }, 
              { line: "They should be segregated for disposition in accordance with provisions in Chapter 3 of this manual" }, 
              { line: "Using pliers as required, rotate the cover (the ridged arming plate in the base end of the marker) clockwise to the armed position as indicated by the notch in the base rim" }, 
              { line: "Push the base plugs into the battery cavity in the marker base" }, 
              { line: "Throw the marker into the water1 Marine Illumination and Smoke Signals, the Pyrotechnic Pistol and Projector Marine illumination signals are unique in appearance and are only fired, launched or deployed with utmost care to ensure that regulations and instructions are rigidly observed" }, 
              { line: "When fired from the proper pistol or projector, a burning star (somewhat like a star from a Roman candle) shoots high into the air" }, 
              { line: "In this section, we will describe the marine illumination, smoke signals, pyrotechnic pistol and projector currently in use" }, 
              { line: "These include the: AN-M37A2 through AN-M39A2 series, double-star illumination signals Mk 1 marine illumination signal and Mk 2 marine smoke signal AN-M8 pyrotechnic pistol Mk 13 marine smoke and illumination signal Mk 1 Navy lights Mk 79 Mod 0 and 21" }, 
              { line: "AN-M37A2 through AN-M39A2 Series, Double-Star Aircraft Illumination Signal The AN-M37A2 through AN-M39A2 series illumination signals are fired from the AN-M8 pyrotechnic pistol for either day or night identification or signaling" }, 
              { line: "Each signal projects two stars of the same color, which burn from 7 to 13 seconds, to an altitude of approximately 250 feet above the point of launch" }, 
              { line: "The 25,000-candlepower stars are visible from 2 to 3 miles in daylight and 5 miles at night in clear weather" }, 
              { line: "The display colors are indicated by ¼-inch bands around the circumference of the signal and by colors on the closing wad" }, 
              { line: "No provision is made for identification by touch as with the Mk 2 marine illumination signal" }, 
              { line: "These signals ignite upon firing since they have no delay fuze" }, 
              { line: "Mk 1 Marine Illumination Signal The Mk 1 marine illumination signal is a general-purpose signal fired from the AN-M8 pyrotechnic pistol" }, 
              { line: "The Mk 1 signal is available in two versions: the Mod 0 and the Mod 1" }, 
              { line: "The Mod 0 produces a red, green, or yellow 7- to 11-second star that falls free and leaves a trail of white light, similar to a comet" }, 
              { line: "The Mod 1 produces a 20- to 30second parachute-suspended red star" }, 
              { line: "Both rounds are expelled from the pyrotechnic pistol by an auxiliary explosive to an approximate altitude of 30 feet" }, 
              { line: "A rocket motor then ignites to propel the signal to a minimum height of 500 feet" }, 
              { line: "It is stabilized in flight by folded fins that spring out once the signal is fired" }, 
              { line: "At the end of its burn, the rocket propellant ignites an expelling charge and the pyrotechnic composition" }, 
              { line: "3 Mk 2 Marine Smoke Signal The Mk 2 marine smoke signal is intended primarily for signaling between ships and aircraft" }, 
              { line: "It consists of a parachute-suspended red smoke display that persists for 20 to 30 seconds at a minimum height of 500 feet" }, 
              { line: "The Mk 2 smoke signal is fired from the AN-M8 pyrotechnic pistol and functions much the same as the Mk 1 marine illumination signal" }, 
              { line: "4 AN-M8 Pyrotechnic Pistol A pistol similar to the Mk 5 pyrotechnic pistol is the AN-M8 pyrotechnic pistol " }, 
              { line: "It can be used with a number of signals of shotgun-shell shape" }, 
              { line: "The AN-M8 pyrotechnic pistol is loaded and fired in much the same fashion as the Mk 5" }, 
              { line: "To open the breech for loading, raise the breechblock and pivot the hinged barrel down for loading and unloading" }, 
              { line: "The same safety and maintenance procedures also apply" }, 
              { line: "WARNING The pyrotechnic pistol is cocked at all times when the breech is closed; it has no positive safety mechanism" }, 
              { line: "Illumination signals Pistol must NOT BE LOADED in the pistol until just before use" }, 
              { line: "Unfired signals must NOT be left in the pistol" }, 
              { line: "Distress and Hand Signals There are three common types of hand-held personnel distress pyrotechnic devices currently found aboard surface ships: the Mk 13 smoke and illumination signal, the Mk 1 Navy light, and the Mk 79 personnel distress signal kit" }, 
              { line: "Mk 13 Marine Smoke and Illumination Signal The Mk 13 marine smoke and illumination signal provides a pillar of smoke by day and a fiery light at night" }, 
              { line: "It is a very comforting thing to have in a life raft or a life vest" }, 
              { line: "The Mk 13 signal is a metal cylinder about 5 1/8 inches long and 1 5/8 inches in diameter" }, 
              { line: "It weighs between 6 and 7 ounces" }, 
              { line: "One end contains a canister that, when ignited, produces orange smoke for about 20 seconds" }, 
              { line: "The other end contains a pyrotechnic flame pellet that will burn for approximately 20 secondsEach end of the metal tube is enclosed by a plastic cap" }, 
              { line: "Under each cap is a pull ring" }, 
              { line: "When you pull the ring, a friction wire attached to its inside surface moves through a cap coated with a composition that ignites (by friction), setting off either the flare or the smoke canister (depending on which ring you pull)" }, 
              { line: "The signal body carries illustrated instructions for use" }, 
              { line: "The flame end plastic cap has three prominent protrusions (beads) across its face to identify it as the end to use at night" }, 
              { line: "When you use the signal, point it away from the face and hold it at arm's length at a 45degree angle after it ignites" }, 
              { line: "After one end of the signal has been used, douse the signal to cool the metal parts" }, 
              { line: "Keep it so that, if necessary, the other end can be used" }, 
              { line: "Each end is separately insulated and waterproofed" }, 
              { line: "NEVER try to use both ends at once" }, 
              { line: "When using the smoke signal, keep it to leeward" }, 
              { line: "These signals are packaged 12 per aluminum container (Mk 3), 9 such containers (108 signals) per wooden box" }, 
              { line: "They may also be packaged 18 signals per aluminum container (M2A1)2 Mk 1 Navy Lights Navy lights are hand torches that burn with a brilliant light visible up to 3 miles at night" }, 
              { line: "They come in two colors: blue and red" }, 
              { line: "Navy blue lights (Mk 1 Mod 1) burn for 75 seconds" }, 
              { line: "Navy red lights (Mk 1 Mod 0) burn for 135 seconds" }, 
              { line: "To ignite the Navy light, tear off the protective strip, remove the cover, and scrape the inverted cover across the top of the paper tube" }, 
              { line: "When you do this, it is advisable to hold the light pointing away from you at an angle of about 45° to avoid contact with hot particles falling off the pyrotechnic candle" }, 
              { line: "Hold the light at that angle while it burns" }, 
              { line: "Navy lights are shipped in metal containers with 6 to 12 lights packed in each" }, 
              { line: "The metal containers are packed into cardboard cartons that hold 12 metal containers" }, 
              { line: "Since these lights deteriorate when exposed to moisture, they should not be removed from their containers until ready for use" }, 
              { line: "For the same reason, keep them away from water or moisture" }, 
              { line: "Navy lights that have been left in open containers for more than 6 months should be turned in to the nearest ammunition depot at the earliest opportunity" }, 
              { line: "Navy lights that have become chemically encrusted or give off an acetic acid (vinegar) odor should be disposed of immediately" }, 
              { line: "Put Navy Lights in a weighted sack and dump them overboard" }, 
              { line: "Mk 79 Mod 0 and Mod 2 Personnel Distress Signal Kits These kits are designed to be used by downed aircrew personnel or personnel in life rafts as a distress signaling device" }, 
              { line: "It is small and lightweight so that it can be carried in pockets of flight suits or on life rafts" }, 
              { line: "The projector aims and fires the signals" }, 
              { line: "Each signal contains a red pyrotechnic starFigure 1-14 The Mk 79 Mod 0 Illumination Signal Kit" }, 
              { line: "On activation, this star is propelled upward to a minimum height of 250 feet" }, 
              { line: "The star burns for a minimum of 4 ½ seconds" }, 
              { line: "The Mk 79 Mod 0 kit consists of one Mk 31 Mod 0 surface signal projector, a plastic bandoleer holding seven Mk 80 hand-fired signals, and an instruction sheet" }, 
              { line: "The Mk 79 Mod 2 kit contains Mk 80 Mod 2 signals" }, 
              { line: "The projector consists of a steel cylinder slightly more than 5 inches long and approximately ½ inch in diameter" }, 
              { line: "The base (or handle) is knurled to provide a more positive gripping surface" }, 
              { line: "Fixed at the base end is an eyebolt to which is tied a 48-inch polypropylene cord, the other end of which is attached to a plastic bandoleer designed to hold seven signals" }, 
              { line: "The firing end of the projector is interiorly threaded for the insertion of a signal" }, 
              { line: "Near this end is a firing slot through which the trigger screw moves when it is released from the angle safety slot" }, 
              { line: "The trigger screw is attached to the firing pin that is forced against the signal primer by a helical spring within the knurled portion of the cylindrical body" }, 
              { line: "Operating Instructions (Mk 31 Mod 0) The Mk 31 Mod 0 projector is operated as follows: 1" }, 
              { line: "Remove the bandoleer and projector from the plastic envelope Cock the firing pin of the projector by moving the trigger screw to the bottom of the vertical slot and slipping it to the right so that it catches at the top of the angular (safety) slot" }, 
              { line: "WARNING The plastic tabs over the signals in the bandoleer protect the percussion primers from being struck accidentally" }, 
              { line: "They should be kept intact until just before loading the signal into the projector Break the protective plastic tab away from the signal in the bandoleer to allow attachment to the projector Mate the projector with the signal and rotate the projector clockwise until the signal is seated 5" }, 
              { line: "Hold the projector over your head with your arm fully extended" }, 
              { line: "The projector should be pointed at a slight angle away from the body" }, 
              { line: "While firmly gripping the projector, fire the signal by slipping the trigger screw to the left out of the safety slot and into the firing slot" }, 
              { line: "NOTE This action should be one continuous movement so that the thumb does not interfere with the forward motion" }, 
              { line: "If the signal fails to fire, pull the trigger screw back to the bottom of the firing slot against the force of the spring, and lift your thumb quickly" }, 
              { line: "WARNING When removing a misfired cartridge, ensure that you keep it pointed in a safe direction and do not place any part of your hand over the discharge end of the cartridge" }, 
              { line: "Unscrew the spent signal case or signal that has failed to fire and discard it by throwing it over the side" }, 
              { line: "Place the trigger screw in the safety slot and reload, as in step 4, if you need to fire another signal" }, 
              { line: "Safety Precautions (Mk 79) The following special safety precautions apply when using the Mk 79 kit: 1" }, 
              { line: "Signals in this kit are ignited by percussion primers, which should be protected against being struck" }, 
              { line: "Protruding tabs of the bandoleer, which extend over the signal bases, prevent accidental striking of the primers" }, 
              { line: "They should not be torn off or bent back except in loading a signal into the projector" }, 
              { line: "The projector should not be loaded until immediately before firing" }, 
              { line: "If a signal is loaded into the projector and is not fired immediately, it should be returned to the bandoleer" }, 
              { line: "WARNING Dented or damaged signals should not be used" }, 
              { line: "Dents or other imperfections might result in violent actions of the signal when fired" }, 
              { line: "Signals should be inspected periodically to ensure that they are not dented or otherwise damaged" }, 
              { line: "Signals should be kept away from fire and other heat sources" }, 
              { line: "The projector trigger screw should be checked frequently to ensure that it is tight" }, 
              { line: "A loose trigger can release the firing pin prematurely and cause injury, or it might fall out and be lost during emergency loading, thereby rendering the projector useless" }, 
              { line: "The trigger screw should be in the safety slot while a signal is being loaded" }, 
              { line: "In the firing of the projector, care should be taken to raise the arm well above the head with the projector held in a vertical position" }, 
              { line: "A loaded projector should never be pointed toward other personnel or toward the body of the user" }, 
              { line: "Pyrotechnic Safety Handling and Stowage The following general information is taken directly from Pyrotechnic, Screening, Marking, and Countermeasure Devices, NAVSEA SW050-AB-MMA-010, chapter 4" }, 
              { line: "Pyrotechnic Safety All pyrotechnic and screening devices, while designed and tested to be safe under normal conditions, can be subject to accidental ignition because of a wide variety of circumstances" }, 
              { line: "The general rule to follow is: Be constantly aware that pyrotechnics contain chemical components that are intended to burn with intense heat, and act accordingly" }, 
              { line: "Pyrotechnic Handling and Stowage All pyrotechnics and smoke-screening devices are designed to withstand normal handling" }, 
              { line: "They should, however, be handled as little as possible to lessen the chances of damage, which might cause accidental ignition or leakage" }, 
              { line: "Many devices contain materials of a dangerous nature and are therefore designed with safety features, which should be maintained in good operating condition" }, 
              { line: "Dents, deformations, or cracks in the outer body may interfere with the proper functioning of these safety features or might cause ignition during handling or stowage" }, 
              { line: "It is therefore imperative that extreme care be taken to prevent damage to containers of pyrotechnics and screening devices and to the devices themselves" }, 
              { line: "Effect of Moisture on Pyrotechnics The proper functioning of pyrotechnic, dye-marking, and screening devices is frequently affected by moisture" }, 
              { line: "Some compositions may become more sensitive and dangerous when exposed to moisture, while others tend to become difficult to ignite and less dependable in operation" }, 
              { line: "Care should be exercised to prevent damage that would interfere with seals because some screening devices produce their smoke by reaction of their chemical contents with moisture in the air" }, 
              { line: "Also, bear in mind that some marine location markers, such as the Mk 58, are saltwater-activated and should be stowed with that in mind" }, 
              { line: "Effect of Temperature on Pyrotechnics Pyrotechnics and some screening devices may become adversely affected by excessively high or variable temperatures" }, 
              { line: "These devices should never be stored where direct rays of the sun could generate excessively high temperature" }, 
              { line: "Stowage should be in dry, wellventilated places that provide the greatest possible protection from such conditions" }, 
              { line: "All Navy pyrotechnics have been designed to withstand temperatures from -65° Fahrenheit to 160° Fahrenheit and, therefore, will probably be safe from deterioration or damage within that range" }, 
              { line: "However, it is recommended that every reasonable effort be made to maintain stowage temperature at not more than 100° Fahrenheit" }, 
              { line: "Specific ammunition stowage temperature requirements for all types of ammunition are addressed in NAVSEA OP 4" }, 
              { line: "Toxic Hazards of Pyrotechnics Many chemicals used in pyrotechnics, screening equipment, and dye-marking devices are poisonous if taken internally" }, 
              { line: "This also applies to the residue of burned pyrotechnics" }, 
              { line: "From the inhalation standpoint, the products of pyrotechnic devices and smoke generators often present a serious problem" }, 
              { line: "Many of the smokes and fumes given off by pyrotechnics and screening devices are considered nontoxic and only mildly irritating to the eyes and nasal passages when encountered in relatively light concentrations out-of doors" }, 
              { line: "Heavy concentrations in closely confined spaces, however, are dangerous and may be lethal because they reduce the amount of oxygen in the air" }, 
              { line: "Anything more than a brief exposure to the gases of combustion, or to screening smokes, should be avoided or should be protected against through the use of an appropriate breathing apparatus" }, 
              { line: "ORDNANCE SAFETY Personnel not familiar with ammunition, or untrained in its use and handling, normally are afraid of the possibility of an explosion" }, 
              { line: "However, when handled properly, Navy explosive ordnance is relatively safe" }, 
              { line: "Ordnance safety regulations are contained in numerous publications" }, 
              { line: "However, you will most often refer to the safety requirements contained in NAVSEA OP-4, Ammunition and Explosives Safety Afloat; OP-5, Ammunition Ashore; Explosives Safety Accidents and Lessons Learned, NAVSEA SW020-AD-SAF-010; and the safety summaries contained in equipment maintenance manuals" }, 
              { line: "Pyrotechnic, Screening, Marking, and Countermeasure Devices, NAVSEA SW050-AB-MMA-010, contains additional information and safety precautions that pertain to the pyrotechnic devices described in this chapter as well as other devices not mentioned" }, 
              { line: "Many of these regulations and precautions embody the lessons learned as a result of actual disasters" }, 
              { line: "THEY MUST BE OBEYED WITHOUT EXCEPTION AND CANNOT BE CHANGED OR DISREGARDED" }, 
              { line: "No matter how dangerous the work, familiarity can lead to carelessness" }, 
              { line: "All personnel involved in the inspection or care of explosives, propellants, and pyrotechnics must EXERCISE UTMOST CARE to ensure that regulations and instructions are rigidly observed" } 
                ];
    }

}