import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-manual',
  templateUrl: './manual.component.html',
  styleUrls: ['./manual.component.scss']
})
export class ManualComponent implements OnInit {

searchTerm = '';
sentences: any[] = [
  { line: "Explosives used to burst a forged steel projectile would be unsuitable as a propelling charge for ejecting and propelling projectiles." },
  { line: "Similarly, the explosives used in initiators, such as in primers and fuzes, are so sensitive to shock that only small quantities can be used safely." },
  { line: "NAVSEA OP-4, Ammunition and Explosives Safety Afloat manual, defines the word explosives as those substances or mixtures of substances that when suitably initiated by flame, spark, etc, undergo rapid chemical reactions resulting in the rapid release of energy." },
  { line: "The release of energy is almost invariably accompanied by a rapid and pronounced rise in pressure and temperature." },
  { line: "The rise in pressure usually, but not necessarily, is a consequence of the rapid generation of gas in a much larger volume than that originally occupied by the explosive." },
  { line: "An \"explosion\" - practically instantaneous and violent release of energy." },
  { line: "It results from the sudden chemical change of a solid or liquid substance into gases." },
  { line: "These gases, expanded by the heat of the chemical change, exert tremendous pressure on their containers and the surrounding atmosphere." },
  { line: "HIGH AND LOW EXPLOSIVES" },
  { line: "Military explosives are divided into two general classes, high explosives and low explosives, according to their rate of decomposition." },
  { line: "High explosives are usually nitration products of organic substances, such as toluene, phenol, pentaerythritol, amines, glycerin, and starch, and may be nitrogen-containing inorganic substances or mixtures of both." },
  { line: "TNT is an example of a high explosive." },
  { line: "A high explosive may be a pure compound or a mixture of several compounds with additives. Additives such as powdered metals (aluminum), plasticizing oils, or waxes, that impart desired stability and performance characteristics." },
  { line: "When initiated by a blow or shock, it will decompose almost instantaneously in a manner similar to an extremely rapid combustion or with rupture and rearrangement of the molecules themselves. Gaseous and solid products of reaction are produced." },
  { line: "The disruptive effect of the reaction makes these explosives valuable as a bursting charge but precludes (makes impossible) their use as a low-explosive propellant." },
  { line: "Low explosives are mostly solid combustible materials that decompose rapidly but do not normally detonate." },
  { line: "This action is known as \"deflagration\". Upon ignition and decomposition, low explosives develop a large volume of gases that produce enough pressure to propel a projectile in a definite direction." },
  { line: "The rate of burning is an important characteristic that depends upon such factors as combustion gas pressure, grain size and form, and composition." },
  { line: "Under certain conditions, low explosives may be made to detonate in the same manner as high explosives." },
  { line: "Characteristics Of Explosive Reactions " },
  { line: "The most important characteristics of explosive reactions are as follows:" },
  { line: "An explosive reaction differs from ordinary combustion in the velocity of the reaction." },
  { line: "The velocity of combustion of explosives may vary within rather wide limits, depending upon the kind of explosive substance and upon its physical state." },
  { line: "For high explosives the velocity, or time of reaction, is high (usually in feet per second), as opposed to low explosives, where the velocity is low (usually in seconds per foot)." },
  { line: "An explosive reaction of a high explosive is always accompanied by the rapid liberation of heat." },
  { line: "The amount of heat represents the energy of the explosive and its potential for doing work." },
  { line: "The principal gaseous products of the more common explosives are carbon dioxide, carbon monoxide, water vapor, nitrogen, nitrogen oxides, hydrogen, methane, and hydrogen cyanide." },
  { line: "Some of these gases are suffocating, some are actively poisonous, and some are combustible." },
  { line: "The flame at the muzzle of a gun results from the burning of these gases." },
  { line: "Solid residues of the explosives remaining in the gun have been known to ignite when brought into contact with air as the breech is opened." },
  { line: "The ignition may come from high temperature of the gas or from the burning residue in the gun bore." },
  { line: "The resulting explosion may transmit flame to the rear of the gun, producing what is called a \"flareback\". This danger has led to the adoption of gas-expelling devices on guns installed in enclosed compartments or mounts." },
  { line: "The high pressure accompanying an explosive reaction is due to the formation of gases that are expanded by the heat liberated in the reaction." },
  { line: "The work that the reaction is capable of performing depends upon the volume of the gases and the amount of heat liberated." },
  { line: "The maximum pressure developed and the way in which the energy of the explosion is applied depends further upon the velocity of the reaction." },
  { line: "When the reaction proceeds at a low velocity, the gases receive heat while being evolved, and the maximum pressure is attained comparatively late in the reaction. If in the explosion of another substance the same volume of gas is produced and the same amount of heat is liberated but at a greater velocity, the maximum pressure will be reached sooner and will be quantitatively greater." },
  { line: "However, disregarding heat losses, the work done will be equal." }, 
{ line: "The rapidity with which an explosive develops its maximum pressure is a measure of the quality known as \"brisance\"." }, 
{ line: "A brisant explosive is one in which the maximum pressure is attained so rapidly that a shock wave is formed, and the net effect is to shatter material surrounding or in contact with it." }, 
{ line: "Thus brisance is a measure of the shattering ability of an explosive." }, 
{ line: "The stability of an explosive is important in determining the length of time it can be kept under normal stowage conditions without deterioration and its adaptability to various military uses." }, 
{ line: "A good, general explosive should stand a reasonable exposure to such extremes as high humidity in a hot climate or cold temperatures of arctic conditions." }, 
{ line: "There is no one temperature of ignition or detonation in an explosive for its behavior when heated depends on two factors: the manner of confinement and the rate and manner of heating." }, 
{ line: "It is usually possible, however, to find a small range of temperatures within which a given explosive will ignite or detonate." }, 
{ line: "These so-called \"ignition temperatures\", or explosion temperatures, are useful in setting limits near which it is certainly unsafe to heat an explosive." }, 
{ line: "When an unconfined explosive is heated sufficiently, it may detonate or simply catch fire and burn." }, 
{ line: "Detonation can occur either immediately or after an interval of burning." }, 
{ line: "In general, the likelihood of detonation rises rapidly with increasing confinement because of the resultant rise in pressure." }, 
{ line: "The adaptability of an explosive to loading requirements is an important factor in fixing its range of usefulness." }, 
{ line: "When projectiles are press-loaded, it is necessary to fill them with a granular explosive." }, 
{ line: "On the other hand, cast-loaded munitions require either an explosive having a relatively low melting point or a thermosetting plastic to act as a casting medium." }, 
{ line: "The amount of energy necessary to initiate an explosion is the measure of the sensitivity of the explosive." }, 
{ line: "Sensitivity is an important consideration in selecting an explosive for a particular purpose." }, 
{ line: "For example, the explosive in an armor-piercing projectile must be relatively insensitive; otherwise, the shock of impact would detonate it before it had penetrated to the point desired." }, 
{ line: "The amount of energy necessary to initiate an explosion is the measure of the sensitivity of the explosive." }, 
{ line: "Sensitivity is an important consideration in selecting an explosive for a particular purpose." }, 
{ line: "For example, the explosive in an armor-piercing projectile must be relatively insensitive; otherwise, the shock of impact would detonate it before it had penetrated to the point desired." }, 
{ line: "By Heat - Low explosives are commonly initiated by the application of heat in some form." }, 
{ line: "High explosives will react when sufficient heat is applied, especially if heat is applied suddenly throughout the mass." }, 
{ line: "Initiation by percussion (direct blow) or by friction is simply initiation by heat derived from the energy of these actions." }, 
{ line: "By Shock (detonation) - High explosives in general, such as the main charges of gun projectiles, require the sudden application of a strong shock to initiate the explosive reaction." }, 
{ line: "This shock or detonation is usually obtained by exploding a smaller charge of a more sensitive high explosive that is in contact with or in close proximity to the main charge" }, 
{ line: "The smaller charge can readily be exploded by heat or shock" }, 
{ line: "By Influence - It has frequently been demonstrated that detonation of an explosive mass can be transmitted to other masses of high explosive in the vicinity without actual contact" }, 
{ line: "It has been generally accepted that such transmission is caused either by the passage of an explosive percussion wave from one mass to the other or by fragments" }, 
{ line: "The second explosion occurring under these conditions is said to be initiated by influence" }, 
{ line: "The result is called a \"sympathetic\" detonation or explosion" }, 
{ line: "The distance through which this action may take place varies with the kinds of explosive used, the intervening medium, and certain other conditions." }, 
{ line: "Classification The classification of explosives thus far has been based on characteristics" }, 
{ line: "A more practical classification, from the standpoint of the GM, is based on military uses of the explosives" }, 
{ line: "These classifications are initiating explosives, booster explosives and igniters, propellants, and the main charge1 Initiating Explosives \"Initiating explosives\" are those explosives that serve to initiate the ignition of propellants and the reaction of high explosives" }, 
{ line: "Initiating explosives function when subjected to heat, impact, or friction" }, 
{ line: "Initiating explosives may function by themselves, as does the primer cap in a small-arms cartridge" }, 
{ line: "However, in most instances the initiating charge is the lead element in what is known as an \"explosive train\" An explosive train uses the impulse of an initiating explosive to initiate the chain reaction that leads to the detonation of a main burster charge or ignition of a propellant" }, 
{ line: "2 Booster Explosives Relatively insensitive disrupting explosives require an intermediate charge to increase the shock of the initiating explosive to ensure proper reaction of the main explosive charge" }, 
{ line: "A booster increases the shock of the initiating explosive to a degree sufficient to explode the disrupting explosive" }, 
{ line: "The basic high-explosive train consists of the initiator, the booster, and the main (burster) charge" }, 
{ line: "However, high-explosive trains are often compounded by the addition of intermediate charges and time delays" }, 
{ line: "An intermediate charge functions between the initial charge and the booster to ensure the detonation of the booster" },
{ line: "The large quantity and relatively slow burning rate of gun propellant requires the use of another type of explosive train" }, 
{ line: "The small flame produced by the initiating charge is insufficient to ignite the propellant grains thoroughly to produce an efficient burning rate of the entire charge" }, 
{ line: "An explosive train consisting of an initiating charge, usually a mixture of lead styphnate and nitrocellulose (NC), detonates to ignite a small black powder booster which, in turn, ignites the larger black powder igniter" }, 
{ line: "The black powder igniter is contained in the extension tube" }, 
{ line: "The primer extension tube of a 5\"/54 powder charge is approximately 20 inches long, contains 52 grams of black powder, and has 32 vent holesFigure 1-2 Typical case electric primerPrimers A primer is a device used to initiate the burning of a propellant charge by means of a flame" }, 
{ line: "Its explosive train normally consists of a small quantity of extremely sensitive primary high explosive which, when detonated, ignites a small black powder booster which, in turn, ignites the black powder igniter" }, 
{ line: "Primers are classified according to the method of initiation (normally percussion or electric) " },
{ line: "All primers function in a similar manner when initiated" }, 
{ line: "Detonators are used in initiating high-explosive bursting charges" }, 
{ line: "They are similar to primers in that they also contain a small quantity of extremely sensitive initiating explosives" }, 
{ line: "However, a detonator will use a high-explosive booster usually made of a more stable substance than the initiating charge but less stable than the main burster" }, 
{ line: "Detonators are also classified according to the methods of initiation, usually electric or percussion" }, 
{ line: "The primary function of a propellant is to provide a pressure that, acting against an object to be propelled, will accelerate the object to the required velocity" }, 
{ line: "This pressure must be controlled so that it will never exceed the strength of the container in which it is produced, such as guns, rocket motor housing, or pyrotechnic pistols" }, 
{ line: "In addition, propellants must be comparatively insensitive to shock" }, 
{ line: "Propellants may be either liquid or solid (Liquid propellants will not be discussed here, since only solid propellants are used in Navy gun ammunition) Propellants can be classified by such terms as single-base, double-base, triple-base, and composite" }, 
{ line: "Single-base propellants contain only one explosive ingredient, NC" }, 
{ line: "Doublebase and triple-base propellants contain, respectively, nitroglycerine (NG) and nitroguanidine (NQ) in addition to NC" }, 
{ line: "Composite propellants are compositions that contain mixtures of fuel and inorganic oxidants" }, 
{ line: "There are combinations of composite and double-base propellants called composite double-base propellants" }, 
{ line: "Solid propellants are manufactured in the form of flakes, balls, sheets, cords, or perforated cylindrical grains" }, 
{ line: "They are made in various shapes to obtain different types of burning actions" }, 
{ line: "In large guns, 40 mm and over, a cylindrical grain with seven perforations is used, while 20-mm guns use a single perforation" }, 
{ line: "Smaller calibers, including small arms, use flake or ball grains" }, 
{ line: "The cylindrical grains are made in various diameters and lengths, but size is normally stated in web thickness " }, 
{ line: "The different types of burning actions are regressive, neutral, and progressive  Figure 1-3 Solid propellant grainsA propellant is said to be \"regressive burning\" when the surface area of the grains decrease as they burn" }, 
{ line: "An example of a \"neutral burning\" grain is a single perforated grain whose inner surface increases and whose outer surface decreases as it burns" }, 
{ line: "The result of these two actions is that the total surface remains the same" }, 
{ line: "As a multiperforated grain burns, its total burning area increases since it burns from the inside to the outside at the same time" }, 
{ line: "Thus it is called \"progressive burning\" "}, 
{ line: "Main Charge The main charge for explosive projectiles, bombs, mines, torpedo warheads, and other bomb type of ammunition is always a high explosive" }, 
{ line: "These substances must meet certain requirements for military use" }, 
{ line: "In general, they must do the following: Be insensitive enough to withstand the shock of handling, of being fired from a gun, and of impact against armor (only in armor-piercing projectiles)  " }, 
{ line: "· · · · Have maximum explosive power" }, 
{ line: "Have stability to withstand adverse stowage conditions" }, 
{ line: "Produce proper fragmentation (only for fragmentation weapons)" }, 
{ line: "Be inexpensive and easy to manufacture from readily available materials "}, 
{ line: "High-explosive charges are loaded into their containers by one of three methods: cast-loading, press-loading, and extrusion (by force)" }, 
{ line: "Cast-loading is performed by pouring the substance as a liquid into a container and letting it solidify" }, 
{ line: "Explosives having no liquid form must be press-loaded (pressed into their container) or incorporated into a liquid casting medium" }, 
{ line: "The combining of certain explosives with plastic binders results in plastic mixtures that can be loaded either by casting or by extrusion (by force)" }, 
{ line: "Specific compounds of these explosives are described in the following section" },  
{ line: "Black Powder Black powder is the oldest explosive known" }, 
{ line: "The ingredients in black powder include saltpeter (potassium nitrate or sodium nitrate), charcoal, and sulfur" }, 
{ line: "It ignites spontaneously at about 300° Celsius (540° Fahrenheit) and develops a fairly high temperature of combustion: 2300° Celsius to 3800° Celsius (4172° Fahrenheit to 6782° Fahrenheit)" }, 
{ line: "The chemical stability of black powder is practically unlimited when stored in airtight containers, but it deteriorates irregularly when exposed to moisture, which it absorbs readily" }, 
{ line: "The term hygroscopic applies to explosives that easily absorb moisture" }, 
{ line: "Black powder is not affected by moderately high temperatures, and it is not subject to spontaneous combustion at ordinary stowage temperatures" }, 
{ line: "It is highly flammable and very sensitive to friction, shock, sparks, and flame" }, 
{ line: "When black powder is ignited, it is extremely quick and violent in its action" }, 
{ line: "The Navy classifies black powder into two types (potassium nitrate and sodium nitrate), depending on the chemical compound used in the base material" }, 
{ line: "These two types are further divided into classes identified by numbers 1 through 9 for potassium nitrate-based black powder and by letters A through C for sodium nitrate-based black powder 2 Uses of Black Powder The range of use of black powder has { line: \"decreased with the development of new chemical compounds but, where smoke is no objection, black powder is considered by many to be the best substance available for transmitting flame and producing a quick, hot flame" }, 
{ line: "Currently, black powder is used by the Navy for the following purposes: · Classes 1 through 9: JATO, rocket igniters, igniter pads, primers, propelling charges for line-throwing guns, expelling charges for base-ejection shells, pyrotechnic items, { line: \"relay pellets, igniting charges for illuminating candles, charges in target practice shells, igniter charges in primer detonators, fuze-delay elements, tracer igniters, delay and igniter charges in primer detonators, practice hand grenade fuzes, and Navy squibs" }, 
{ line: "Classes A through C: Saluting charges and practice bombs" }, 
{ line: "Black Powder as a Propellant Black powder as a gun propellant has several disadvantages: (1) it leaves a large amount of residue, (2) it produces large quantities of smoke, (3) it causes rapid erosion of the gun bore, and (4) its velocity of { line: \"reaction is too rapid\" " }, 
{ line: "For these reasons and the fact that black powder charges do not provide the reproducible results required of modern guns, it was abandoned as a propellant around 1888" }, 
{ line: "This abandonment was hastened by the development of NC 2 Nitrocellulos (NC) NC was first prepared in 1838" }, 
{ line: "However, two main problems had to be solved before it could be used as a gun propellant" }, 
{ line: "First, the velocity of the explosion had to be reduced so that the charge weight required to propel the projectile would not shatter the gun tube" }, 
{ line: "Second, the density had to be increased so that a given charge weight would pack into a reasonable space" }, 
{ line: "The first problem was solved in part by igniting NC instead of firing it with a detonator" }, 
{ line: "The solution to the second problem actually solved both" }, 
{ line: "In 1886, Vielle first colloided or gelatinized NC with alcohol and ether and, thus reduced the burning rate to acceptable levels" }, 
{ line: "The procedure significantly increased the loading density of NC, establishing it as the foundational element in gun propellants used through the present day" }, 
{ line: "Further developments resulted in materials that could be added to improve stowage qualities, reduce or eliminate flash, reduce hygroscopicity, reduce flame temperature, and even increase the propellant force or impetus" }, 
{ line: "Smokeless Powder Smokeless powder is the propellant used in the propelling charges for Navy gun ammunition" }, 
{ line: "It is a uniform ether-alcohol colloid of purified NC to which is added a small quantity of diphenylamine or ethyl centralite to assist in preserving the stability of the powder" }, 
{ line: "Smokeless powder is basically unstable since it contains NC and two volatile substances-ether and alcohol" }, 
{ line: "Its length of usefulness depends largely on the conditions under which it is stowed" }, 
{ line: "Moisture or heat speeds its deterioration; a combination of the two has extremely damaging effects" }, 
{ line: "Classification of Smokeless Powder Smokeless powder is classified into two types: single-base and multi-base" }, 
{ line: "Single-base Powder Multibase powder uses NG and/or NQ in addition to NC as explosive ingredients" }, 
{ line: "Such propellants are commonly called double-base (NC and NG) and triple-base (NC, NG, and NQ)" }, 
{ line: "One double-base and one triple-base propellant are in use today2 Multibase Powder Multibase powder uses NG and/or NQ in addition to NC as explosive ingredients" }, 
{ line: "Such propellants are commonly called double-base (NC and NG) and triple-base (NC, NG, and NQ)" }, 
{ line: "One double-base and one triple-base propellant are in use today" }, 
{ line: "Index of Smokeless Powder Smokeless powder types are assigned class designation letters that designate the chemical makeup of the powder as follows: " }, 
{ line: "SP - Smokeless powder " }, 
{ line: "B - Blended " }, 
{ line: "C - Stabilized by ethyl centralite " }, 
{ line: "D - Stabilized by diphenylamine " }, 
{ line: "F - Flashless powder " }, 
{ line: "G - Includes nitroglycerine and nitroguanidine " }, 
{ line: "N - Nonhygroscopic " }, 
{ line: "W - Reworked by grinding " }, 
{ line: "X - Water-drying process" }, 
{ line: "These letters are followed by a number that indicates the sequence of manufacture" }, 
{ line: "The combination of the letters and the number is termed the index or the lot of the powder" }, 
{ line: "The combinations of the class designation letters are described below" }, 
{ line: "SPC - SPC is a cool-burning, single-base smokeless powder (SP) with ethyl centralite (C) as a stabilizer" }, 
{ line: "SPCF - is a single-base smokeless powder similar to SPC type of powder but containing a flash suppressor to render the powder flashless" }, 
{ line: "SPCF is found in all 5i\"/54 universal charge, full-service propelling charges" }, 
{ line: "SPCG - is a multibase smokeless powder stabilized with ethyl centralite and includes NG and NQ in its composition" }, 
{ line: "Although the designation letter for flashless powder (F) is not used, SPCG is a flashless powder" }, 
{ line: "SPD - is a single-base smokeless powder stabilized with diphenylamine" }, 
{ line: "SPDB - is a blend of diphenylamine-stabilized powders of different lots" }, 
{ line: "The purpose of blending is to provide a uniform index of ample size and desired character from smaller remnant lots" }, 
{ line: "SPDF - is a diphenylamine-stabilized smokeless powder to which a flash inhibitor, such as potassium sulfate, has been added" }, 
{ line: "SPDN is a diphenylamine-stabilized smokeless powder to which nonvolatile materials are added to reduce the hygroscopic tendencies of the propellant" }, 
{ line: "The N stands for nonhygroscopic" }, 
{ line: "SPWF - is a flashless powder made by the reworking of ordinary nonflashless powder" }, 
{ line: "M-6 and M-6+2 propellant designations - equate to the SPDN and SPDF (respectively) descriptions previously provided" }, 
{ line: "These designations are used to describe the propellants used in 76-mm ammunition" }, 
{ line: "The +2 refers to a 2% mixture of potassium sulfate" }, 
{ line: "SPDX - is a diphenylamine-stabilized smokeless powder that is water-dried" }, 
{ line: "In the water-drying process, the powder is seasoned in tanks of warm water to remove volatile solvents, followed by a brief period of air drying" } 
  ];
  
  constructor() { }

  ngOnInit() {
  }

}
